version: '3.8'

services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prueba
      POSTGRES_DB: blog_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Solo para desarrollo local, ¡no exponer en producción!
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    build: ./api
    command: uvicorn app.main:app --reload --host 0.0.0.0
    environment:
      DATABASE_URL: postgresql://postgres:prueba:5432/blog_db
    depends_on:
      - database
    ports:
      - "8000:8000"

  web:
    build: ./web
    command: flask run --host 0.0.0.0 --port 5000 --reload
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "5000:5000"

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
    db_data: